#
# Autogenerated by Thrift Compiler (0.11.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
from thrift.protocol.TProtocol import TProtocolException
from thrift.TRecursive import fix_spec

import sys

from thrift.transport import TTransport
all_structs = []


class UUID(object):
    """
    UUIDs in this system MUST behave in the following manner:
     * When used as a component id, UUID MUST be the same for each data payload and SHOULD
       be the same every time the system restarts EXCEPT WHEN the component itself is changed
       (e.g. a detector is replaced with a new one)
     * When used as a algorithm id, UUID MUST be the same for each data payload and SHOULD
       be the same every time the system restarts EXCEPT WHEN the algorithm code is changed
     * When used as a unit id, UUID MUST be the same for each message and SHOULD be the
       same every time the system restarts EXCEPT WHEN the definition has changed
     * When used as a message, bounding box, and marker id, the UUID SHOULD be random

     When generating a UUID that is to be constant then UUID version 3 or 5 MUST be used.
     When generating a UUID that is to be random, then UUID version 4 MUST be used.


    Attributes:
     - mostSignificantBits
     - leastSignificantBits
    """


    def __init__(self, mostSignificantBits=None, leastSignificantBits=None,):
        self.mostSignificantBits = mostSignificantBits
        self.leastSignificantBits = leastSignificantBits

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.I64:
                    self.mostSignificantBits = iprot.readI64()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.I64:
                    self.leastSignificantBits = iprot.readI64()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('UUID')
        if self.mostSignificantBits is not None:
            oprot.writeFieldBegin('mostSignificantBits', TType.I64, 1)
            oprot.writeI64(self.mostSignificantBits)
            oprot.writeFieldEnd()
        if self.leastSignificantBits is not None:
            oprot.writeFieldBegin('leastSignificantBits', TType.I64, 2)
            oprot.writeI64(self.leastSignificantBits)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(UUID)
UUID.thrift_spec = (
    None,  # 0
    (1, TType.I64, 'mostSignificantBits', None, None, ),  # 1
    (2, TType.I64, 'leastSignificantBits', None, None, ),  # 2
)
fix_spec(all_structs)
del all_structs
