#
# Autogenerated by Thrift Compiler (0.11.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
from thrift.protocol.TProtocol import TProtocolException
from thrift.TRecursive import fix_spec

import sys

from thrift.transport import TTransport
all_structs = []


class CylindricalDimensions(object):
    """
    Attributes:
     - radius: Centimeters
     - length: Centimeters
    """


    def __init__(self, radius=None, length=None,):
        self.radius = radius
        self.length = length

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.DOUBLE:
                    self.radius = iprot.readDouble()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.DOUBLE:
                    self.length = iprot.readDouble()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('CylindricalDimensions')
        if self.radius is not None:
            oprot.writeFieldBegin('radius', TType.DOUBLE, 1)
            oprot.writeDouble(self.radius)
            oprot.writeFieldEnd()
        if self.length is not None:
            oprot.writeFieldBegin('length', TType.DOUBLE, 2)
            oprot.writeDouble(self.length)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class SphericalDimensions(object):
    """
    Attributes:
     - radius: Centimeters
    """


    def __init__(self, radius=None,):
        self.radius = radius

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.DOUBLE:
                    self.radius = iprot.readDouble()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('SphericalDimensions')
        if self.radius is not None:
            oprot.writeFieldBegin('radius', TType.DOUBLE, 1)
            oprot.writeDouble(self.radius)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class RectangularDimensions(object):
    """
    Attributes:
     - depth: Centimeters
     - width: Centimeters
     - length: Centimeters
    """


    def __init__(self, depth=None, width=None, length=None,):
        self.depth = depth
        self.width = width
        self.length = length

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.DOUBLE:
                    self.depth = iprot.readDouble()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.DOUBLE:
                    self.width = iprot.readDouble()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.DOUBLE:
                    self.length = iprot.readDouble()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('RectangularDimensions')
        if self.depth is not None:
            oprot.writeFieldBegin('depth', TType.DOUBLE, 1)
            oprot.writeDouble(self.depth)
            oprot.writeFieldEnd()
        if self.width is not None:
            oprot.writeFieldBegin('width', TType.DOUBLE, 2)
            oprot.writeDouble(self.width)
            oprot.writeFieldEnd()
        if self.length is not None:
            oprot.writeFieldBegin('length', TType.DOUBLE, 3)
            oprot.writeDouble(self.length)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class Dimensions(object):
    """
    Attributes:
     - cylindricalDimensions
     - sphericalDimensions
     - rectangularDimensions
    """


    def __init__(self, cylindricalDimensions=None, sphericalDimensions=None, rectangularDimensions=None,):
        self.cylindricalDimensions = cylindricalDimensions
        self.sphericalDimensions = sphericalDimensions
        self.rectangularDimensions = rectangularDimensions

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRUCT:
                    self.cylindricalDimensions = CylindricalDimensions()
                    self.cylindricalDimensions.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.STRUCT:
                    self.sphericalDimensions = SphericalDimensions()
                    self.sphericalDimensions.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.STRUCT:
                    self.rectangularDimensions = RectangularDimensions()
                    self.rectangularDimensions.read(iprot)
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('Dimensions')
        if self.cylindricalDimensions is not None:
            oprot.writeFieldBegin('cylindricalDimensions', TType.STRUCT, 1)
            self.cylindricalDimensions.write(oprot)
            oprot.writeFieldEnd()
        if self.sphericalDimensions is not None:
            oprot.writeFieldBegin('sphericalDimensions', TType.STRUCT, 2)
            self.sphericalDimensions.write(oprot)
            oprot.writeFieldEnd()
        if self.rectangularDimensions is not None:
            oprot.writeFieldBegin('rectangularDimensions', TType.STRUCT, 3)
            self.rectangularDimensions.write(oprot)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(CylindricalDimensions)
CylindricalDimensions.thrift_spec = (
    None,  # 0
    (1, TType.DOUBLE, 'radius', None, None, ),  # 1
    (2, TType.DOUBLE, 'length', None, None, ),  # 2
)
all_structs.append(SphericalDimensions)
SphericalDimensions.thrift_spec = (
    None,  # 0
    (1, TType.DOUBLE, 'radius', None, None, ),  # 1
)
all_structs.append(RectangularDimensions)
RectangularDimensions.thrift_spec = (
    None,  # 0
    (1, TType.DOUBLE, 'depth', None, None, ),  # 1
    (2, TType.DOUBLE, 'width', None, None, ),  # 2
    (3, TType.DOUBLE, 'length', None, None, ),  # 3
)
all_structs.append(Dimensions)
Dimensions.thrift_spec = (
    None,  # 0
    (1, TType.STRUCT, 'cylindricalDimensions', [CylindricalDimensions, None], None, ),  # 1
    (2, TType.STRUCT, 'sphericalDimensions', [SphericalDimensions, None], None, ),  # 2
    (3, TType.STRUCT, 'rectangularDimensions', [RectangularDimensions, None], None, ),  # 3
)
fix_spec(all_structs)
del all_structs
